/* eslint-disable @typescript-eslint/no-empty-function */

export default (staffType: 'entertainer' | 'handyman' | 'mechanic' | 'security'): any => ({
    peepType: 'staff',
    staffType,
    colour: 0,
    costume: 0,
    orders: 0,
    patrolArea: {
        tiles: [],
        clear: (): void => {},
        add: (): void => {},
        remove: (): void => {},
        contains: (): boolean => true,
    },
    name: 'test',
    destination: {
        x: 0,
        y: 0,
    },
    energy: 0,
    energyTarget: 0,
    getFlag: () => true,
    setFlag: () => true,
    id: 0,
    type: 'staff',
    x: 0,
    y: 0,
    z: 0,
    remove: (): void => {},
    availableCostumes: [],
    availableAnimations: [],
    getAnimationSpriteIds: () => [],
    animation: "walking",
    animationOffset: 0,
    animationLength: 0,
    direction: 0,
});
